name: Attributes


on:
  workflow_dispatch:
  schedule:
    - cron: '15 30 * * *' 


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scraping script
      run: |
        python scraper/scraper/Listing_Url/attribute.py 

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add scraper/scraper/Listing_Url/json_file/listing_attribute.json
        git commit -m 'Update listing_attribute.json with latest Airbnb details'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


