name: Attributes

on:
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraping script
      run: python scraper/scraper/Listing_Url/attribute.py  # Replace 'your_script.py' with the actual script name if different

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add json_file/listing_attribute.json
        git commit -m 'Update listing_attribute.json with new data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
