name: Air bnb Metrics Login

on:
  workflow_dispatch: # This allows manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight (UTC)

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip ffmpeg
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        rm google-chrome-stable_current_amd64.deb
        python -m pip install --upgrade pip
        pip install pandas pyppeteer google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Start Video Recording
      run: |
        ffmpeg -y -video_size 1920x1080 -framerate 25 -f x11grab -i :99.0 video_output.mp4 &
      env:
        DISPLAY: ":99"

    - name: Run Python Script
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }} # Your Google Sheets credentials
        AIRBNB_USER_SECRET: ${{ secrets.AIRBNB_USER_SECRET }}
        AIRBNB_PASSW_SECRET: ${{ secrets.AIRBNB_PASSW_SECRET }}
      run: |
        python scraper/scraper/Listing_Url/metrics_airbnb.py

    - name: Stop Video Recording
      run: |
        pkill ffmpeg || true

    - name: Upload Video Recording
      uses: actions/upload-artifact@v3
      with:
        name: video-output
        path: video_output.mp4
