name: Metrics Login Airbnb

on:
  workflow_dispatch: # This allows manual triggering of the workflow
  schedule:
    - cron: "0 0 * * *"  # This runs the workflow every day at midnight (UTC)

jobs:
  run_puppeteer_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        rm google-chrome-stable_current_amd64.deb
        npm install puppeteer

    - name: Run Puppeteer Script
      env:
        AIRBNB_USER_SECRET: ${{ secrets.AIRBNB_USER_SECRET }}
        AIRBNB_PASSW_SECRET: ${{ secrets.AIRBNB_PASSW_SECRET }}
      run: |
        node scraper/scraper/Listing_Url/metrics_airbnb.js
