name: Run Batch 53

on:
  workflow_dispatch:
  schedule:
    - cron: "40 4 * * *" # 12:40 PM PH time
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gspread oauth2client pandas gspread-dataframe
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run scraper script
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      run: |
        BATCH_ID=Batch53 python scraper/scraper/Listing_Url/simultaneous.py
