name: Runner 2

on:
  push:
#  schedule:
#    - cron: '15 16 * * *'  # Runs at 4:15 PM UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper script
      run: |
        BATCH_ID=Batch1 python scraper/scraper/Listing_Url/simultaneous.py

    - name: Pull latest changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git add scraper/scraper/Listing_Url/output/final_results.json
        git commit -m "Update final_results.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
